// Format: render one brand's resolved tokens as CSS. Two kinds of output share
// the file:
//   - colors + dimensions → custom properties in `:root`. Colors are theme-aware:
//     the light value is zipped with the matching dark value (supplied via
//     `options.darkTokens`, keyed by token path) into `light-dark()`.
//   - typography composites → utility classes (`.typography-body-default { … }`).
//     The `typography/css-class` transform has already built each token's
//     declaration block; this format only wraps it in the selector and indents it.
// See context/output.md.

import type { Format, TransformedToken } from 'style-dictionary/types';

export const CSS_LIGHT_DARK = 'css/light-dark';

/** Options the CSS builder threads through the file config to this format. */
export interface CssLightDarkOptions {
  /** Token path (`a.b.c`) → resolved dark-mode value, for the `light-dark()` pair. */
  darkTokens: Map<string, string>;
  /** Brand name, for the file header. */
  brand: string;
  /** Pretty path of the destination, for the build log line. */
  label: string;
}

interface CssVar {
  name: string;
  value: string;
}

interface CssClass {
  selector: string;
  /** The declaration block (one `property: value;` per line), unindented. */
  declarations: string;
}

function colorVar(
  token: TransformedToken,
  darkTokens: Map<string, string>,
  skipped: string[]
): CssVar | null {
  const light = typeof token.$value === 'string' ? token.$value : null;
  const dark = darkTokens.get(token.path.join('.')) ?? light;
  if (light === null || dark == null) {
    skipped.push(`${token.name} (color)`);
    return null;
  }
  return { name: token.name, value: `light-dark(${light}, ${dark})` };
}

const indent = (block: string): string =>
  block
    .split('\n')
    .map((line) => `  ${line}`)
    .join('\n');

function render(brand: string, vars: CssVar[], classes: CssClass[]): string {
  const declarations = vars.map((v) => `  --${v.name}: ${v.value};`).join('\n');
  const classBlocks = classes
    .map((c) => `${c.selector} {\n${indent(c.declarations)}\n}`)
    .join('\n\n');

  return `/* Generated by @acronis-platform/style-dictionary — DO NOT EDIT. */
/* Source: @acronis-platform/design-tokens • brand: ${brand} */

:root {
  color-scheme: light dark;

${declarations}
}

[data-theme='light'] {
  color-scheme: light;
}

[data-theme='dark'] {
  color-scheme: dark;
}

${classBlocks}
`;
}

export const cssLightDark: Format = {
  name: CSS_LIGHT_DARK,
  format: ({ dictionary, file }) => {
    const { darkTokens, brand, label } = file.options as CssLightDarkOptions;
    const vars: CssVar[] = [];
    const classes: CssClass[] = [];
    const skipped: string[] = [];

    for (const token of dictionary.allTokens) {
      if (token.$type === 'color') {
        const cssVar = colorVar(token, darkTokens, skipped);
        if (cssVar) vars.push(cssVar);
      } else if (token.$type === 'typography') {
        // `typography/css-class` transformed the composite into a declaration block.
        if (typeof token.$value === 'string' && token.$value.length) {
          classes.push({ selector: `.${token.name}`, declarations: token.$value });
        } else {
          skipped.push(`${token.name} (typography)`);
        }
      } else if (typeof token.$value === 'string') {
        // dimension / scalar — already CSS-ready.
        vars.push({ name: token.name, value: token.$value });
      } else {
        // gradient and any other unhandled type are out of MVP scope.
        skipped.push(`${token.name} (${token.$type})`);
      }
    }

    vars.sort((a, b) => a.name.localeCompare(b.name));
    classes.sort((a, b) => a.selector.localeCompare(b.selector));

    const note = skipped.length
      ? ` (${skipped.length} unsupported tokens skipped: ${skipped.join(', ')})`
      : '';
    console.log(
      `✓ ${label} — ${vars.length} variables, ${classes.length} typography classes${note}`
    );
    return render(brand, vars, classes);
  },
};
